version: '3.3'
services:
  web: &web
    build:
      context: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      DATABASE_URL: postgres://postgres:@postgres/review_test
    ports:
      - 3210:3000
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle


volumes:
  bundle:

networks:
  default:
    external:
      name: styleport_backend
